#!/bin/bash
# Terminal launcher for StreamDiffusion

# Determine the path to the StreamDiffusion repo
SCRIPT_DIR=$(dirname "$0")
SD_DIR=$(cd "$SCRIPT_DIR/../../.." && pwd)
echo "StreamDiffusion directory: $SD_DIR"

# Create a launcher that can be used from anywhere
cat > ~/.local/bin/streamdiffusion-launcher.sh << EOF
#!/bin/bash
# StreamDiffusion Launcher
# Automatically generated by fix script

# Activate conda environment if available and named SD
if command -v conda &> /dev/null; then
  echo "Conda found, activating environment 'SD' if it exists..."
  conda activate SD 2>/dev/null || echo "Conda environment 'SD' not found, continuing with current environment."
fi

# Set the environment variables
export PYTHONPATH="$SD_DIR:\$PYTHONPATH"

# Change to the application directory
cd "$SD_DIR/demo/realtime-img2img"

# Run the application
./run_mac.sh
EOF

# Make launcher executable
mkdir -p ~/.local/bin
chmod +x ~/.local/bin/streamdiffusion-launcher.sh

# Add path to .zshrc if not already present
if ! grep -q "PATH=\$PATH:~/.local/bin" ~/.zshrc; then
  echo 'export PATH=$PATH:~/.local/bin' >> ~/.zshrc
  echo "Added ~/.local/bin to PATH in .zshrc"
  echo "Please restart your terminal or run 'source ~/.zshrc' to update your PATH"
fi

echo "Created global launcher at ~/.local/bin/streamdiffusion-launcher.sh"
echo "You can now run StreamDiffusion from any terminal with: streamdiffusion-launcher.sh"
